server:
  port: 8081
  servlet:
    context-path: /member # \u9879\u76EE\u8BBF\u95EE\u8DEF\u5F84
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/train
    username: root
    password: hutao1224